version: "3"
services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: node-app-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  redis:
    container_name: node-app-redis
    image: redis:6.0.12
    ports:
      - "6379:6379"
volumes:
  mongo-db: